services:
  db:
    container_name: app-db
    image: postgres:16
    environment:
      POSTGRES_DB: "appdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  app-db-data:
